"""initial schema

Revision ID: 1632922265b2
Revises: 
Create Date: 2026-08-29 22:17:23.464296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1632922265b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('police_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('station', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tourists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digital_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_number', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('itinerary', sa.Text(), nullable=False),
    sa.Column('emergency_contacts', sa.Text(), nullable=False),
    sa.Column('trip_start', sa.DateTime(), nullable=False),
    sa.Column('trip_end', sa.DateTime(), nullable=False),
    sa.Column('last_lat', sa.Float(), nullable=True),
    sa.Column('last_lng', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('safety_score', sa.Float(), nullable=False),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tourists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tourists_digital_id'), ['digital_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('polygon', sa.Text(), nullable=False),
    sa.Column('crime_index', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_tourist_id'), ['tourist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_zone_id'), ['zone_id'], unique=False)

    op.create_table('id_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('hashed_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('id_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_id_blocks_tourist_id'), ['tourist_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('assigned_unit_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_unit_id'], ['police_units.id'], ),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_tourist_id'), ['tourist_id'], unique=False)

    op.create_table('location_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_pings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_pings_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_pings_tourist_id'), ['tourist_id'], unique=False)
        batch_op.create_index('ix_location_pings_tourist_timestamp', ['tourist_id', 'timestamp'], unique=False)

    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_events_incident_id'), ['incident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_events_incident_id'))

    op.drop_table('incident_events')
    with op.batch_alter_table('location_pings', schema=None) as batch_op:
        batch_op.drop_index('ix_location_pings_tourist_timestamp')
        batch_op.drop_index(batch_op.f('ix_location_pings_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_location_pings_timestamp'))

    op.drop_table('location_pings')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_tourist_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('id_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_id_blocks_tourist_id'))

    op.drop_table('id_blocks')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_zone_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    op.drop_table('zones')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tourists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tourists_digital_id'))

    op.drop_table('tourists')
    op.drop_table('police_units')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
