"""add efirs table

Revision ID: a75d53582983
Revises: 7d4b05c51dd6
Create Date: 2026-08-29 22:45:40.136905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75d53582983'
down_revision: Union[str, Sequence[str], None] = '7d4b05c51dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('efirs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fir_number', sa.String(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('last_known_lat', sa.Float(), nullable=True),
    sa.Column('last_known_lng', sa.Float(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('document_hash', sa.String(), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('efirs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_efirs_fir_number'), ['fir_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_efirs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_efirs_tourist_id'), ['tourist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('efirs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_efirs_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_efirs_incident_id'))
        batch_op.drop_index(batch_op.f('ix_efirs_fir_number'))

    op.drop_table('efirs')
    # ### end Alembic commands ###
