"""Model evaluation reporting.

The training pipeline writes `ml_models/metrics.json` with measured precision,
recall, ROC-AUC, R2 and cluster quality. Nothing surfaced it, so the evaluation
evidence for the project's three models existed only as a file on disk. This
serves it to the dashboard.
"""
import json
import os
from datetime import UTC, datetime

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.api.deps import require_admin
from app.core.config import settings
from app.db.session import get_db
from app.ml import registry
from app.models.tourist import LocationPing
from app.models.user import User
from app.services import drift

router = APIRouter(prefix="/ml", tags=["ml"])


def _metrics_path() -> str:
    return os.path.join(settings.ML_MODELS_DIR, "metrics.json")


@router.get("/metrics")
def model_metrics(_: User = Depends(require_admin)):
    """Evaluation report for every trained model."""
    path = _metrics_path()
    if not os.path.exists(path):
        raise HTTPException(
            status_code=404,
            detail="No metrics report found. Run: python -m app.ml.train_all",
        )
    with open(path, encoding="utf-8") as f:
        report = json.load(f)

    trained_at = datetime.fromtimestamp(os.path.getmtime(path), tz=UTC)
    return {
        "trained_at": trained_at.isoformat(),
        "models": report,
        # Stated up front rather than left for a reader to discover.
        "training_data": {
            "source": "synthetic",
            "reproducible": True,
            "random_seed": 42,
            "note": (
                "Models are trained on synthetic data generated by "
                "app/ml/generate_data.py with a fixed seed, so reported metrics "
                "are reproducible. Real deployment would retrain on operational "
                "ping and incident history; the feature contracts are unchanged."
            ),
        },
    }


@router.get("/status")
def model_status(db: Session = Depends(get_db), _: User = Depends(require_admin)):
    """Which model artifacts are actually loaded, and how much live data exists.

    `ml_service` silently falls back to rule-based scoring when an artifact is
    missing, which is right for uptime but means a demo can look healthy while
    running no ML at all. This makes that state visible.
    """
    artifacts = {
        "anomaly_isoforest.joblib": "IsolationForest (anomaly detection)",
        "anomaly_scaler.joblib": "StandardScaler (anomaly features)",
        "safety_rf.joblib": "RandomForestRegressor (safety score)",
    }
    loaded = {
        name: {
            "description": desc,
            "present": os.path.exists(os.path.join(settings.ML_MODELS_DIR, name)),
        }
        for name, desc in artifacts.items()
    }
    all_present = all(v["present"] for v in loaded.values())

    return {
        "artifacts": loaded,
        "inference_mode": "model" if all_present else "rule-based fallback",
        "hotzones_available": os.path.exists(
            os.path.join(settings.ML_MODELS_DIR, "hotzones.json")
        ),
        "live_pings_collected": db.query(LocationPing).count(),
        "anomalies_flagged": db.query(LocationPing).filter(
            LocationPing.is_anomaly.is_(True)
        ).count(),
    }


@router.get("/feature-contract")
def feature_contract(_: User = Depends(require_admin)):
    """The exact feature vectors the models consume, in order.

    Training and inference must agree on ordering; `ml_service` is the single
    source of truth for both, and this exposes it for the report/viva.
    """
    return {
        "anomaly": {
            "features": ["speed_kmh", "dist_from_prev_m", "inactivity_min",
                         "dist_from_route_m"],
            "produced_by": "ml_service.anomaly_features()",
            "output": "{is_anomaly: bool, score: float in [0,1]}",
        },
        "safety": {
            "features": ["zone_risk", "hour", "anomaly_score", "crime_index",
                         "weather_risk"],
            "produced_by": "ml_service.safety_features()",
            "output": "safety score, float in [0,100] (higher = safer)",
        },
        "thresholds": {
            "route_deviation_m": settings.ROUTE_DEVIATION_THRESHOLD_M,
            "anomaly_incident_dedupe_minutes": settings.ANOMALY_INCIDENT_DEDUPE_MINUTES,
            "safety_bands": {"safe": ">=75", "moderate": "50-74",
                             "risky": "25-49", "danger": "<25"},
        },
    }


@router.get("/registry")
def model_registry(_: User = Depends(require_admin)):
    """Version history for every trained model: when each version was
    trained, the hash of the data it saw, and its metrics -- so a model can
    be traced and rolled back rather than trusted blindly."""
    reg = registry.load_registry(settings.ML_MODELS_DIR)
    if not reg:
        raise HTTPException(
            status_code=404,
            detail="No model registry found. Run: python -m app.ml.train_all",
        )
    return reg


@router.get("/drift")
def model_drift(db: Session = Depends(get_db), _: User = Depends(require_admin)):
    """Population Stability Index comparing live ping traffic against the
    distribution the anomaly model was trained on."""
    return drift.get_drift_report(db)
